import web3Util from './web3';
const address = '0x314e34EFfdA6999CF633c737daC961B0907061eF';
const abi = [{
	"inputs": [{
		"internalType": "string",
		"name": "_uriPrefix",
		"type": "string"
	}, {
		"internalType": "string",
		"name": "_contractUri",
		"type": "string"
	}],
	"stateMutability": "nonpayable",
	"type": "constructor"
}, {
	"inputs": [],
	"name": "ApprovalCallerNotOwnerNorApproved",
	"type": "error"
}, {
	"inputs": [],
	"name": "ApprovalQueryForNonexistentToken",
	"type": "error"
}, {
	"inputs": [],
	"name": "BalanceQueryForZeroAddress",
	"type": "error"
}, {
	"inputs": [{
		"internalType": "uint256",
		"name": "numerator",
		"type": "uint256"
	}, {
		"internalType": "uint256",
		"name": "denominator",
		"type": "uint256"
	}],
	"name": "ERC2981InvalidDefaultRoyalty",
	"type": "error"
}, {
	"inputs": [{
		"internalType": "address",
		"name": "receiver",
		"type": "address"
	}],
	"name": "ERC2981InvalidDefaultRoyaltyReceiver",
	"type": "error"
}, {
	"inputs": [{
		"internalType": "uint256",
		"name": "tokenId",
		"type": "uint256"
	}, {
		"internalType": "uint256",
		"name": "numerator",
		"type": "uint256"
	}, {
		"internalType": "uint256",
		"name": "denominator",
		"type": "uint256"
	}],
	"name": "ERC2981InvalidTokenRoyalty",
	"type": "error"
}, {
	"inputs": [{
		"internalType": "uint256",
		"name": "tokenId",
		"type": "uint256"
	}, {
		"internalType": "address",
		"name": "receiver",
		"type": "address"
	}],
	"name": "ERC2981InvalidTokenRoyaltyReceiver",
	"type": "error"
}, {
	"inputs": [],
	"name": "MintERC2309QuantityExceedsLimit",
	"type": "error"
}, {
	"inputs": [],
	"name": "MintToZeroAddress",
	"type": "error"
}, {
	"inputs": [],
	"name": "MintZeroQuantity",
	"type": "error"
}, {
	"inputs": [],
	"name": "NotCompatibleWithSpotMints",
	"type": "error"
}, {
	"inputs": [{
		"internalType": "address",
		"name": "owner",
		"type": "address"
	}],
	"name": "OwnableInvalidOwner",
	"type": "error"
}, {
	"inputs": [{
		"internalType": "address",
		"name": "account",
		"type": "address"
	}],
	"name": "OwnableUnauthorizedAccount",
	"type": "error"
}, {
	"inputs": [],
	"name": "OwnerQueryForNonexistentToken",
	"type": "error"
}, {
	"inputs": [],
	"name": "OwnershipNotInitializedForExtraData",
	"type": "error"
}, {
	"inputs": [],
	"name": "SequentialMintExceedsLimit",
	"type": "error"
}, {
	"inputs": [],
	"name": "SequentialUpToTooSmall",
	"type": "error"
}, {
	"inputs": [],
	"name": "SpotMintTokenIdTooSmall",
	"type": "error"
}, {
	"inputs": [],
	"name": "TokenAlreadyExists",
	"type": "error"
}, {
	"inputs": [],
	"name": "TransferCallerNotOwnerNorApproved",
	"type": "error"
}, {
	"inputs": [],
	"name": "TransferFromIncorrectOwner",
	"type": "error"
}, {
	"inputs": [],
	"name": "TransferToNonERC721ReceiverImplementer",
	"type": "error"
}, {
	"inputs": [],
	"name": "TransferToZeroAddress",
	"type": "error"
}, {
	"inputs": [],
	"name": "URIQueryForNonexistentToken",
	"type": "error"
}, {
	"anonymous": false,
	"inputs": [{
		"indexed": true,
		"internalType": "address",
		"name": "owner",
		"type": "address"
	}, {
		"indexed": true,
		"internalType": "address",
		"name": "approved",
		"type": "address"
	}, {
		"indexed": true,
		"internalType": "uint256",
		"name": "tokenId",
		"type": "uint256"
	}],
	"name": "Approval",
	"type": "event"
}, {
	"anonymous": false,
	"inputs": [{
		"indexed": true,
		"internalType": "address",
		"name": "owner",
		"type": "address"
	}, {
		"indexed": true,
		"internalType": "address",
		"name": "operator",
		"type": "address"
	}, {
		"indexed": false,
		"internalType": "bool",
		"name": "approved",
		"type": "bool"
	}],
	"name": "ApprovalForAll",
	"type": "event"
}, {
	"anonymous": false,
	"inputs": [{
		"indexed": true,
		"internalType": "address",
		"name": "addr",
		"type": "address"
	}],
	"name": "Burn",
	"type": "event"
}, {
	"anonymous": false,
	"inputs": [{
		"indexed": true,
		"internalType": "uint256",
		"name": "fromTokenId",
		"type": "uint256"
	}, {
		"indexed": false,
		"internalType": "uint256",
		"name": "toTokenId",
		"type": "uint256"
	}, {
		"indexed": true,
		"internalType": "address",
		"name": "from",
		"type": "address"
	}, {
		"indexed": true,
		"internalType": "address",
		"name": "to",
		"type": "address"
	}],
	"name": "ConsecutiveTransfer",
	"type": "event"
}, {
	"anonymous": false,
	"inputs": [{
		"indexed": true,
		"internalType": "address",
		"name": "previousOwner",
		"type": "address"
	}, {
		"indexed": true,
		"internalType": "address",
		"name": "newOwner",
		"type": "address"
	}],
	"name": "OwnershipTransferred",
	"type": "event"
}, {
	"anonymous": false,
	"inputs": [{
		"indexed": true,
		"internalType": "address",
		"name": "from",
		"type": "address"
	}, {
		"indexed": true,
		"internalType": "address",
		"name": "to",
		"type": "address"
	}, {
		"indexed": true,
		"internalType": "uint256",
		"name": "tokenId",
		"type": "uint256"
	}],
	"name": "Transfer",
	"type": "event"
}, {
	"anonymous": false,
	"inputs": [{
		"indexed": false,
		"internalType": "address",
		"name": "_from",
		"type": "address"
	}, {
		"indexed": false,
		"internalType": "uint256",
		"name": "_amount",
		"type": "uint256"
	}],
	"name": "TransferReceived",
	"type": "event"
}, {
	"inputs": [{
		"internalType": "address",
		"name": "to",
		"type": "address"
	}, {
		"internalType": "uint256",
		"name": "tokenId",
		"type": "uint256"
	}],
	"name": "approve",
	"outputs": [],
	"stateMutability": "payable",
	"type": "function"
}, {
	"inputs": [{
		"internalType": "address",
		"name": "owner",
		"type": "address"
	}],
	"name": "balanceOf",
	"outputs": [{
		"internalType": "uint256",
		"name": "",
		"type": "uint256"
	}],
	"stateMutability": "view",
	"type": "function"
}, {
	"inputs": [],
	"name": "contractURI",
	"outputs": [{
		"internalType": "string",
		"name": "",
		"type": "string"
	}],
	"stateMutability": "view",
	"type": "function"
}, {
	"inputs": [],
	"name": "cost",
	"outputs": [{
		"internalType": "uint256",
		"name": "",
		"type": "uint256"
	}],
	"stateMutability": "view",
	"type": "function"
}, {
	"inputs": [],
	"name": "emergencyWithdraw",
	"outputs": [],
	"stateMutability": "nonpayable",
	"type": "function"
}, {
	"inputs": [{
		"internalType": "uint256",
		"name": "tokenId",
		"type": "uint256"
	}],
	"name": "getApproved",
	"outputs": [{
		"internalType": "address",
		"name": "",
		"type": "address"
	}],
	"stateMutability": "view",
	"type": "function"
}, {
	"inputs": [{
		"internalType": "address",
		"name": "owner",
		"type": "address"
	}, {
		"internalType": "address",
		"name": "operator",
		"type": "address"
	}],
	"name": "isApprovedForAll",
	"outputs": [{
		"internalType": "bool",
		"name": "",
		"type": "bool"
	}],
	"stateMutability": "view",
	"type": "function"
}, {
	"inputs": [],
	"name": "isSaleActive",
	"outputs": [{
		"internalType": "bool",
		"name": "",
		"type": "bool"
	}],
	"stateMutability": "view",
	"type": "function"
}, {
	"inputs": [],
	"name": "maxMintAmountPerTx",
	"outputs": [{
		"internalType": "uint256",
		"name": "",
		"type": "uint256"
	}],
	"stateMutability": "view",
	"type": "function"
}, {
	"inputs": [],
	"name": "maxSupply",
	"outputs": [{
		"internalType": "uint256",
		"name": "",
		"type": "uint256"
	}],
	"stateMutability": "view",
	"type": "function"
}, {
	"inputs": [{
		"internalType": "uint256",
		"name": "_mintAmount",
		"type": "uint256"
	}],
	"name": "mint",
	"outputs": [{
		"internalType": "uint256[]",
		"name": "",
		"type": "uint256[]"
	}],
	"stateMutability": "payable",
	"type": "function"
}, {
	"inputs": [],
	"name": "name",
	"outputs": [{
		"internalType": "string",
		"name": "",
		"type": "string"
	}],
	"stateMutability": "view",
	"type": "function"
}, {
	"inputs": [{
		"internalType": "uint256",
		"name": "_tokenId",
		"type": "uint256"
	}],
	"name": "open",
	"outputs": [],
	"stateMutability": "nonpayable",
	"type": "function"
}, {
	"inputs": [],
	"name": "owner",
	"outputs": [{
		"internalType": "address",
		"name": "",
		"type": "address"
	}],
	"stateMutability": "view",
	"type": "function"
}, {
	"inputs": [{
		"internalType": "uint256",
		"name": "tokenId",
		"type": "uint256"
	}],
	"name": "ownerOf",
	"outputs": [{
		"internalType": "address",
		"name": "",
		"type": "address"
	}],
	"stateMutability": "view",
	"type": "function"
}, {
	"inputs": [],
	"name": "renounceOwnership",
	"outputs": [],
	"stateMutability": "nonpayable",
	"type": "function"
}, {
	"inputs": [{
		"internalType": "uint256",
		"name": "tokenId",
		"type": "uint256"
	}, {
		"internalType": "uint256",
		"name": "salePrice",
		"type": "uint256"
	}],
	"name": "royaltyInfo",
	"outputs": [{
		"internalType": "address",
		"name": "",
		"type": "address"
	}, {
		"internalType": "uint256",
		"name": "",
		"type": "uint256"
	}],
	"stateMutability": "view",
	"type": "function"
}, {
	"inputs": [{
		"internalType": "address",
		"name": "from",
		"type": "address"
	}, {
		"internalType": "address",
		"name": "to",
		"type": "address"
	}, {
		"internalType": "uint256",
		"name": "tokenId",
		"type": "uint256"
	}],
	"name": "safeTransferFrom",
	"outputs": [],
	"stateMutability": "payable",
	"type": "function"
}, {
	"inputs": [{
		"internalType": "address",
		"name": "from",
		"type": "address"
	}, {
		"internalType": "address",
		"name": "to",
		"type": "address"
	}, {
		"internalType": "uint256",
		"name": "tokenId",
		"type": "uint256"
	}, {
		"internalType": "bytes",
		"name": "_data",
		"type": "bytes"
	}],
	"name": "safeTransferFrom",
	"outputs": [],
	"stateMutability": "payable",
	"type": "function"
}, {
	"inputs": [{
		"internalType": "address",
		"name": "operator",
		"type": "address"
	}, {
		"internalType": "bool",
		"name": "approved",
		"type": "bool"
	}],
	"name": "setApprovalForAll",
	"outputs": [],
	"stateMutability": "nonpayable",
	"type": "function"
}, {
	"inputs": [{
		"internalType": "string",
		"name": "_contractUri",
		"type": "string"
	}],
	"name": "setContractURI",
	"outputs": [],
	"stateMutability": "nonpayable",
	"type": "function"
}, {
	"inputs": [{
		"internalType": "uint256",
		"name": "_cost",
		"type": "uint256"
	}],
	"name": "setCost",
	"outputs": [],
	"stateMutability": "nonpayable",
	"type": "function"
}, {
	"inputs": [{
		"internalType": "uint256",
		"name": "_maxMintAmountPerTx",
		"type": "uint256"
	}],
	"name": "setMaxMintAmountPerTx",
	"outputs": [],
	"stateMutability": "nonpayable",
	"type": "function"
}, {
	"inputs": [],
	"name": "setSaleActive",
	"outputs": [],
	"stateMutability": "nonpayable",
	"type": "function"
}, {
	"inputs": [{
		"internalType": "string",
		"name": "_uriPrefix",
		"type": "string"
	}],
	"name": "setUriPrefix",
	"outputs": [],
	"stateMutability": "nonpayable",
	"type": "function"
}, {
	"inputs": [{
		"internalType": "string",
		"name": "_uriSuffix",
		"type": "string"
	}],
	"name": "setUriSuffix",
	"outputs": [],
	"stateMutability": "nonpayable",
	"type": "function"
}, {
	"inputs": [{
		"internalType": "bytes4",
		"name": "interfaceId",
		"type": "bytes4"
	}],
	"name": "supportsInterface",
	"outputs": [{
		"internalType": "bool",
		"name": "",
		"type": "bool"
	}],
	"stateMutability": "view",
	"type": "function"
}, {
	"inputs": [],
	"name": "symbol",
	"outputs": [{
		"internalType": "string",
		"name": "",
		"type": "string"
	}],
	"stateMutability": "view",
	"type": "function"
}, {
	"inputs": [{
		"internalType": "uint256",
		"name": "_tokenId",
		"type": "uint256"
	}],
	"name": "tokenURI",
	"outputs": [{
		"internalType": "string",
		"name": "",
		"type": "string"
	}],
	"stateMutability": "view",
	"type": "function"
}, {
	"inputs": [],
	"name": "totalMint",
	"outputs": [{
		"internalType": "uint256",
		"name": "",
		"type": "uint256"
	}],
	"stateMutability": "view",
	"type": "function"
}, {
	"inputs": [],
	"name": "totalSupply",
	"outputs": [{
		"internalType": "uint256",
		"name": "result",
		"type": "uint256"
	}],
	"stateMutability": "view",
	"type": "function"
}, {
	"inputs": [{
		"internalType": "address",
		"name": "from",
		"type": "address"
	}, {
		"internalType": "address",
		"name": "to",
		"type": "address"
	}, {
		"internalType": "uint256",
		"name": "tokenId",
		"type": "uint256"
	}],
	"name": "transferFrom",
	"outputs": [],
	"stateMutability": "payable",
	"type": "function"
}, {
	"inputs": [{
		"internalType": "address",
		"name": "newOwner",
		"type": "address"
	}],
	"name": "transferOwnership",
	"outputs": [],
	"stateMutability": "nonpayable",
	"type": "function"
}, {
	"inputs": [],
	"name": "uriPrefix",
	"outputs": [{
		"internalType": "string",
		"name": "",
		"type": "string"
	}],
	"stateMutability": "view",
	"type": "function"
}, {
	"inputs": [],
	"name": "uriSuffix",
	"outputs": [{
		"internalType": "string",
		"name": "",
		"type": "string"
	}],
	"stateMutability": "view",
	"type": "function"
}, {
	"stateMutability": "payable",
	"type": "receive"
}]

export default new class {
  get instance() {
    if (web3Util.web3) {
      return new window.web3.eth.Contract(abi, address);
    }
    return null
  }
};
